### ISSUE TITLE
Incorrect comment

### ISSUE THREAD

**Issue by the-programmer** [suda/RCSwitch#1]
Hi, just a quick note that I found a (minor) issue in the code.
In the file "RCSwitch.cpp" there are the functions:

``` C++
void RCSwitch::switchOn(char sFamily, int nGroup, int nDevice);
//and
void RCSwitch::switchOff(char sFamily, int nGroup, int nDevice);
```

In the code comments is stated that the family is allowed from a to f, however in the code (getCodeWordC) a to p is allowed.

In this case the code comment is wrong since the switch on the remote allows for a to p.

**Comment by the-programmer** [comment]
@suda, thanks for the fix. However you fixed it the wrong way. This since the remote allows for the letters A to P. 

A edit in the comments was better.

**Comment by suda** [comment]
@the-programmer you're right. I've rushed and though about 0...f instead of a...p range.
